import { useState } from "react";
import {
  Activity, AlertTriangle, BarChart3, Bell, Building2, Check, ChevronDown,
  ChevronLeft, ChevronRight, CircleDollarSign, ClipboardList, Copy, CreditCard,
  Download, Ellipsis, Gauge, DoorOpen, LayoutDashboard,
  Mail, Menu, MessageSquare, MoreHorizontal, Plus, Receipt, RefreshCw, Search,
  Settings, Shield, SlidersHorizontal, TestTube2, TrendingDown, TrendingUp, UserPlus,
  Users, WalletCards, X, Zap,
} from "lucide-react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie,
  PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
} from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";

type View = "overview" | "estates" | "health" | "revenue" | "errors" | "staff" | "billing" | "settings";
type EstateTab = "Overview" | "Gates" | "Residents" | "Maintenance" | "Manager Activity" | "Billing";

const estates = [
  { name: "Kyalami Hills", province: "Gauteng", units: 248, health: 94, manager: "Sipho Dlamini", gate: "Online", mrr: "R 18 500.00", status: "Active", adoption: 89 },
  { name: "Waterfall Ridge", province: "Gauteng", units: 186, health: 82, manager: "Thandi Nkosi", gate: "Online", mrr: "R 14 200.00", status: "Active", adoption: 76 },
  { name: "Atlantic Terraces", province: "Western Cape", units: 310, health: 71, manager: "Lisa Adams", gate: "Degraded", mrr: "R 22 000.00", status: "Active", adoption: 64 },
  { name: "Umhlanga Gardens", province: "KwaZulu-Natal", units: 122, health: 57, manager: "Mandla Zulu", gate: "Offline", mrr: "R 9 800.00", status: "Suspended", adoption: 52 },
  { name: "Silver Lakes North", province: "Gauteng", units: 96, health: 68, manager: "Unassigned", gate: "Pending", mrr: "R 7 500.00", status: "Setup Incomplete", adoption: 41 },
];

const months = [
  { month: "Jan", revenue: 58800, expenses: 17800, profit: 41000, tickets: 142, resolution: 18 },
  { month: "Feb", revenue: 61200, expenses: 19400, profit: 41800, tickets: 128, resolution: 16 },
  { month: "Mar", revenue: 64500, expenses: 21100, profit: 43400, tickets: 153, resolution: 14 },
  { month: "Apr", revenue: 66700, expenses: 18900, profit: 47800, tickets: 119, resolution: 13 },
  { month: "May", revenue: 69800, expenses: 22600, profit: 47200, tickets: 136, resolution: 12 },
  { month: "Jun", revenue: 72000, expenses: 20100, profit: 51900, tickets: 108, resolution: 10 },
];

const errors = [
  { time: "12 Jun 2026 · 14:32", severity: "Critical", category: "Gate Offline", description: "North vehicle gate connection lost", estate: "Umhlanga Gardens", status: "Open" },
  { time: "12 Jun 2026 · 13:18", severity: "Warning", category: "Guest Code", description: "SMS delivery failed after 3 attempts", estate: "Atlantic Terraces", status: "Open" },
  { time: "12 Jun 2026 · 11:04", severity: "Warning", category: "Login Anomaly", description: "Multiple failed manager login attempts", estate: "Silver Lakes North", status: "Investigating" },
  { time: "12 Jun 2026 · 09:47", severity: "Critical", category: "Billing Failure", description: "Monthly subscription payment failed", estate: "Umhlanga Gardens", status: "Open" },
  { time: "11 Jun 2026 · 17:22", severity: "Info", category: "App Crash", description: "Resident app crash report received", estate: "Kyalami Hills", status: "Resolved" },
];

function statusTone(value: string | number) {
  if (typeof value === "number") return value >= 80 ? "success" : value >= 60 ? "warning" : "error";
  if (["Active", "Online", "Paid", "Resolved", "Connected", "Valid"].includes(value)) return "success";
  if (["Warning", "Pending", "Setup Incomplete", "Degraded", "Investigating"].includes(value)) return "warning";
  if (["Critical", "Offline", "Suspended", "Overdue", "Open"].includes(value)) return "error";
  return "neutral";
}

function Badge({ children, tone }: { children: React.ReactNode; tone?: string }) {
  return <span className={`status-badge status-${tone ?? statusTone(String(children))}`}>{children}</span>;
}

function StatCard({ label, value, note, icon: Icon, alert }: { label: string; value: string; note: string; icon: typeof Activity; alert?: boolean }) {
  return (
    <article className="metric-card">
      <div className="metric-top"><span>{label}</span><Icon className={alert ? "text-error" : "text-muted-foreground"} /></div>
      <strong className="metric-value">{value}</strong>
      <span className="metric-note">{note}</span>
    </article>
  );
}

function PageHeader({ eyebrow, title, subtitle, children }: { eyebrow?: string; title: string; subtitle?: string; children?: React.ReactNode }) {
  return (
    <header className="page-header">
      <div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{subtitle && <p className="page-subtitle">{subtitle}</p>}</div>
      {children && <div className="header-actions">{children}</div>}
    </header>
  );
}

function Panel({ title, action, children, className = "" }: { title: string; action?: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section className={`panel ${className}`}><div className="panel-header"><h2>{title}</h2>{action}</div>{children}</section>;
}

function MiniTooltip({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; name: string }>; label?: string }) {
  if (!active || !payload?.length) return null;
  return <div className="chart-tooltip"><span>{label}</span>{payload.map((item) => <strong key={item.name}>{item.name}: {item.value.toLocaleString("en-ZA")}</strong>)}</div>;
}

function EstateTable({ onOpen, compact = false }: { onOpen: (name: string) => void; compact?: boolean }) {
  return (
    <div className="table-scroll"><table><thead><tr><th>Estate name</th>{!compact && <th>Province</th>}<th>Units</th><th>Health</th>{!compact && <th>Manager</th>}<th>Gate</th>{!compact && <th>MRR</th>}<th>{compact ? "Last activity" : "Status"}</th>{!compact && <th />}</tr></thead>
      <tbody>{estates.map((estate) => <tr key={estate.name} onClick={() => onOpen(estate.name)} className="clickable-row">
        <td><button className="table-link">{estate.name}</button></td>{!compact && <td>{estate.province}</td>}<td className="data-text">{estate.units}</td><td><Badge tone={statusTone(estate.health)}>{estate.health}%</Badge></td>{!compact && <td>{estate.manager}</td>}<td><Badge>{estate.gate}</Badge></td>{!compact && <td className="data-text">{estate.mrr}</td>}<td>{compact ? "4 min ago" : <Badge>{estate.status}</Badge>}</td>{!compact && <td><Button variant="ghost" size="icon" aria-label="More actions"><MoreHorizontal /></Button></td>}
      </tr>)}</tbody></table></div>
  );
}

function Overview({ openEstate, navigate }: { openEstate: (name: string) => void; navigate: (view: View) => void }) {
  return <>
    <PageHeader eyebrow="Portfolio overview" title="Good afternoon, Bryson" subtitle="Here’s what’s happening across Estavo today."><Button variant="outline"><Download /> Export snapshot</Button></PageHeader>
    <div className="stats-grid"><StatCard label="Total estates" value="5" note="4 active · 1 suspended" icon={Building2}/><StatCard label="Total residents" value="3 842" note="2 914 registered · 928 pending" icon={Users}/><StatCard label="Monthly recurring revenue" value="R 72 000.00" note="+4.2% from last month" icon={CircleDollarSign}/><StatCard label="Active system alerts" value="4" note="2 critical · 2 warnings" icon={AlertTriangle} alert/></div>
    <div className="dashboard-split">
      <Panel title="Estate health summary" action={<button className="text-link" onClick={() => navigate("estates")}>View all estates <ChevronRight /></button>}><EstateTable onOpen={openEstate} compact /></Panel>
      <Panel title="Live system alerts" action={<button className="text-link" onClick={() => navigate("errors")}>View all alerts <ChevronRight /></button>}>
        <div className="alert-feed">{errors.slice(0,4).map((e) => <button className="alert-item" key={e.time+e.category} onClick={() => navigate("errors")}><span className={`alert-dot status-${statusTone(e.severity)}`} /><span><strong>{e.description}</strong><small>{e.estate} · {e.time.split(" · ")[1]}</small></span><ChevronRight /></button>)}</div>
      </Panel>
    </div>
    <div className="chart-grid-three">
      <Panel title="Monthly revenue trend"><div className="chart-box"><ResponsiveContainer><AreaChart data={months}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-foreground)" stopOpacity={.25}/><stop offset="100%" stopColor="var(--chart-foreground)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip content={<MiniTooltip />}/><Area type="monotone" dataKey="revenue" stroke="var(--chart-foreground)" fill="url(#revenueFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>
      <Panel title="Ticket volume"><div className="chart-box"><ResponsiveContainer><BarChart data={months}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip content={<MiniTooltip />}/><Bar dataKey="tickets" fill="var(--chart-muted)" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></Panel>
      <Panel title="Resident app adoption"><div className="adoption-list">{estates.slice(0,4).map(e=><div key={e.name}><span><b>{e.name}</b><em>{e.adoption}%</em></span><div className="progress"><i style={{width:`${e.adoption}%`}} /></div></div>)}</div></Panel>
    </div>
  </>;
}

function EstatesPage({ openEstate, openWizard }: { openEstate: (name: string) => void; openWizard: () => void }) {
  const [filter,setFilter]=useState("All"); const [query,setQuery]=useState("");
  const shown=estates.filter(e=>(filter==="All"||filter==="Needs Attention"&&e.health<70||e.status===filter)&&e.name.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Portfolio" title="Estates" subtitle="Manage every estate connected to the Estavo platform."><Button onClick={openWizard}><Plus/>Add new estate</Button></PageHeader>
    <div className="toolbar"><div className="chips">{["All","Active","Suspended","Needs Attention"].map(x=><Button key={x} variant={filter===x?"default":"outline"} size="sm" onClick={()=>setFilter(x)}>{x}</Button>)}</div><label className="search"><Search/><Input placeholder="Search estates..." value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
    <Panel title={`${shown.length} estates`} action={<Button variant="outline" size="sm"><SlidersHorizontal/>Filters</Button>}><EstateTable onOpen={openEstate}/></Panel>
  </>;
}

function EstateDetail({ name, close }: { name: string; close: () => void }) {
  const estate=estates.find(e=>e.name===name)??estates[0]; const [tab,setTab]=useState<EstateTab>("Overview"); const tabs:EstateTab[]=["Overview","Gates","Residents","Maintenance","Manager Activity","Billing"];
  return <><button className="breadcrumb" onClick={close}><ChevronLeft/> Estates <span>/</span> {estate.name}</button>
    <PageHeader title={estate.name} subtitle={`${estate.province} · ${estate.units} units`}><Badge>{estate.status}</Badge><Button variant="outline">Edit estate</Button><Button variant="destructive">Suspend estate</Button><Button>Open as manager <ChevronRight/></Button></PageHeader>
    <nav className="tabs">{tabs.map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
    {tab==="Overview"&&<><div className="stats-grid"><StatCard label="Health score" value={`${estate.health}%`} note="↑ 3 points this month" icon={Gauge}/><StatCard label="Registered residents" value="389" note={`${estate.adoption}% adoption`} icon={Users}/><StatCard label="Open tickets" value="12" note="3 high priority" icon={ClipboardList}/><StatCard label="Gate uptime" value="99.7%" note="Last 30 days" icon={DoorOpen}/></div><div className="detail-grid"><Panel title="Estate health"><div className="health-focus"><strong>{estate.health}</strong><Badge tone={statusTone(estate.health)}>Healthy</Badge><p>Performance is trending upwards across gate uptime, response time and resident adoption.</p></div></Panel><Panel title="Quick access"><div className="quick-links">{tabs.slice(1).map(x=><Button variant="outline" key={x} onClick={()=>setTab(x)}>{x}<ChevronRight/></Button>)}</div></Panel></div></>}
    {tab==="Gates"&&<GatesTab/>}{tab==="Residents"&&<ResidentsTab/>}{tab==="Maintenance"&&<MaintenanceTab/>}{tab==="Manager Activity"&&<ManagerTab estate={estate.name}/>} {tab==="Billing"&&<EstateBillingTab/>}
  </>;
}

function GatesTab(){return <><div className="gate-grid">{["North vehicle gate","South pedestrian gate","Service boom"].map((x,i)=><article className="panel" key={x}><div className="panel-header"><span className="icon-box"><DoorOpen/></span><Badge>{i===2?"Offline":"Online"}</Badge></div><h3>{x}</h3><p>Last ping: {i===2?"11 Jun 2026 · 22:04":"12 Jun 2026 · 14:31"}</p><div className="card-actions"><Button variant="outline"><TestTube2/>Test connection</Button><Button variant="ghost">Connection log</Button></div></article>)}</div><Panel title="Full access log" action={<Button variant="outline"><Download/>Export CSV</Button>}><SimpleTable headers={["Timestamp","Person / unit","Type","Gate","Code"]} rows={[["12 Jun 2026 · 14:31","Unit 42","Resident","North vehicle","RSD-2048"],["12 Jun 2026 · 14:29","Visitor · Unit 18","Guest","South pedestrian","G-8821"],["12 Jun 2026 · 14:21","Delivery","Guest","North vehicle","G-4117"]]}/></Panel></>}
function ResidentsTab(){return <Panel title="Residents" action={<div className="header-actions"><Button variant="outline">Import CSV</Button><Button><UserPlus/>Add resident</Button></div>}><SimpleTable headers={["Unit","Name","Email","Status","Last active","Actions"]} rows={[["12","Nandi Mokoena","nandi@example.co.za",<Badge>Active</Badge>,"12 Jun · 14:22",<RowActions labels={["Edit unit","Reset access","Deactivate"]}/>],["18","James van Wyk","james@example.co.za",<Badge>Active</Badge>,"12 Jun · 13:51",<RowActions labels={["Edit unit","Reset access","Deactivate"]}/>],["27","Ayanda Khumalo","ayanda@example.co.za",<Badge tone="warning">Invited</Badge>,"Never",<RowActions labels={["Edit unit","Reset access","Deactivate"]}/>]]}/></Panel>}
function MaintenanceTab(){return <Panel title="All maintenance tickets" action={<div className="chips"><Button size="sm">Table</Button><Button size="sm" variant="outline">Kanban</Button></div>}><SimpleTable headers={["Ticket","Category","Unit","Priority","Status","Assignee","Actions"]} rows={[["#MT-1042","Plumbing","Unit 18",<Badge tone="error">High</Badge>,"In progress","T. Naidoo",<RowActions labels={["Reassign","Close","Escalate"]}/>],["#MT-1039","Electrical","Unit 72",<Badge tone="warning">Medium</Badge>,"Submitted","Unassigned",<RowActions labels={["Reassign","Close","Escalate"]}/>],["#MT-1027","Landscaping","Common area",<Badge>Low</Badge>,"Resolved","M. Jacobs",<RowActions labels={["Reassign","Close","Escalate"]}/>]]}/></Panel>}
function ManagerTab({estate}:{estate:string}){return <div className="detail-grid"><Panel title="Estate manager"><div className="profile-card"><div className="avatar">SD</div><div><h3>Sipho Dlamini</h3><p>sipho@{estate.toLowerCase().replaceAll(" ","")}.co.za</p><Badge>Active</Badge></div></div><dl className="definition-list"><div><dt>Role</dt><dd>Estate manager</dd></div><div><dt>Last login</dt><dd>12 Jun 2026 · 13:58</dd></div></dl><div className="stack-actions"><Button><MessageSquare/>Message manager</Button><Button variant="outline">Reassign manager</Button><Button variant="destructive">Revoke access</Button></div></Panel><Panel title="Recent activity"><ActivityList/></Panel></div>}
function EstateBillingTab(){return <><div className="stats-grid"><StatCard label="Current plan" value="Growth" note="Custom estate plan" icon={WalletCards}/><StatCard label="Monthly fee" value="R 18 500.00" note="Next invoice 01 Jul 2026" icon={CircleDollarSign}/><StatCard label="Billing status" value="Paid" note="Last paid 01 Jun 2026" icon={Check}/><StatCard label="Outstanding" value="R 0.00" note="No overdue invoices" icon={Receipt}/></div><Panel title="Invoice history" action={<div className="header-actions"><Button variant="outline">Edit subscription amount</Button><Button>Mark as paid manually</Button></div>}><SimpleTable headers={["Invoice","Date","Amount","Status","Action"]} rows={[["INV-2026-0612","01 Jun 2026","R 18 500.00",<Badge>Paid</Badge>,<Button variant="ghost" size="sm"><Download/>PDF</Button>],["INV-2026-0511","01 May 2026","R 18 500.00",<Badge>Paid</Badge>,<Button variant="ghost" size="sm"><Download/>PDF</Button>]]}/></Panel></>}

function HealthPage({openEstate}:{openEstate:(name:string)=>void}){return <><PageHeader eyebrow="Analytics" title="Health & Performance" subtitle="Portfolio performance signals and operational health."><Button variant="outline">13 May — 12 Jun 2026 <ChevronDown/></Button></PageHeader><div className="stats-grid"><StatCard label="Average health score" value="74.4%" note="↑ 2.8 this period" icon={Gauge}/><StatCard label="Total gate uptime" value="97.8%" note="Weighted across 12 gates" icon={DoorOpen}/><StatCard label="Avg resolution time" value="10.2 hrs" note="↓ 1.8 hrs this period" icon={Activity}/><StatCard label="Resident app adoption" value="64.4%" note="Portfolio average" icon={Users}/></div><div className="chart-grid-two"><Panel title="Estate health scores"><div className="health-bars">{estates.map(e=><button key={e.name} onClick={()=>openEstate(e.name)}><span>{e.name}<b>{e.health}%</b></span><div className="progress"><i className={`status-${statusTone(e.health)}`} style={{width:`${e.health}%`}}/></div></button>)}</div></Panel><Panel title="Gate uptime by estate"><ChartBars dataKey="health"/></Panel><Panel title="Ticket volume & resolution trend"><ComboChart/></Panel><Panel title="Resident adoption by estate"><ChartBars dataKey="adoption"/></Panel></div><Panel title="Alerts this period"><SimpleTable headers={["Estate","Alert type","Count","Trend","Last occurred"]} rows={[["Umhlanga Gardens","Gate offline","8",<span className="trend-down"><TrendingUp/>+3</span>,"12 Jun · 14:32"],["Atlantic Terraces","Guest code delivery","5",<span className="trend-up"><TrendingDown/>-2</span>,"12 Jun · 13:18"],["Silver Lakes North","Login failures","3","—","12 Jun · 11:04"]]}/></Panel></>}

function RevenuePage(){const [expenseOpen,setExpenseOpen]=useState(false);return <><PageHeader eyebrow="Analytics" title="Revenue & Financials" subtitle="Track portfolio revenue, expenses and profitability."><Button variant="outline">June 2026 <ChevronDown/></Button><Button variant="outline"><Download/>CSV</Button><Button variant="outline"><Download/>PDF</Button></PageHeader><div className="stats-grid stats-grid-six"><StatCard label="MRR" value="R 72 000.00" note="June 2026" icon={CircleDollarSign}/><StatCard label="ARR" value="R 864 000.00" note="Annualised" icon={TrendingUp}/><StatCard label="Expenses" value="R 20 100.00" note="This month" icon={Receipt}/><StatCard label="Net profit" value="R 51 900.00" note="72.1% margin" icon={WalletCards}/><StatCard label="YTD revenue" value="R 393 000.00" note="Jan — Jun" icon={BarChart3}/><StatCard label="YTD net profit" value="R 272 200.00" note="69.3% margin" icon={Gauge}/></div><Panel title="Revenue breakdown"><SimpleTable headers={["Estate","Plan","Monthly fee","Status","Last payment","Actions"]} rows={estates.slice(0,4).map(e=>[e.name,"Growth",e.mrr,<Badge tone={e.status==="Suspended"?"error":"success"}>{e.status==="Suspended"?"Overdue":"Paid"}</Badge>,"01 Jun 2026",<RowActions labels={["Edit amount","Send reminder"]}/>])}/></Panel><div className="section-heading"><div><h2>Expense ledger</h2><p>Operational expenses recorded this month.</p></div><Button onClick={()=>setExpenseOpen(true)}><Plus/>Add expense</Button></div><Panel title="June expenses"><SimpleTable headers={["Date","Description","Category","Amount","Added by","Actions"]} rows={[["10 Jun 2026","Cloud infrastructure","Infrastructure","R 9 800.00","Bryson Mabilo",<RowActions labels={["Edit","Delete"]}/>],["05 Jun 2026","Messaging services","Software","R 3 240.00","N. Mahlangu",<RowActions labels={["Edit","Delete"]}/>],["01 Jun 2026","Support contractor","Staff","R 7 060.00","Bryson Mabilo",<RowActions labels={["Edit","Delete"]}/>]]}/></Panel><div className="chart-grid-three"><Panel title="Revenue vs expenses"><DualBar/></Panel><Panel title="Net profit trend"><LineOnly/></Panel><Panel title="Revenue by estate"><RevenuePie/></Panel></div>{expenseOpen&&<Modal title="Add expense" close={()=>setExpenseOpen(false)}><FormField label="Description" placeholder="e.g. Cloud infrastructure"/><SelectField label="Category" options={["Infrastructure","Software","Staff","Marketing","Other"]}/><div className="form-grid"><FormField label="Amount (ZAR)" placeholder="R 0.00"/><FormField label="Date" type="date"/></div><FormField label="Notes (optional)" placeholder="Add context..."/><div className="modal-actions"><Button variant="outline" onClick={()=>setExpenseOpen(false)}>Cancel</Button><Button onClick={()=>setExpenseOpen(false)}>Save expense</Button></div></Modal>}</>}

function ErrorsPage(){const [selected,setSelected]=useState<(typeof errors)[0]|null>(null);const [severity,setSeverity]=useState("All");return <><PageHeader eyebrow="Analytics" title="System Errors & Failures" subtitle="Investigate failures and resolve platform incidents."><Button variant="outline">13 May — 12 Jun 2026 <ChevronDown/></Button></PageHeader><div className="stats-grid"><StatCard label="Total errors" value="32" note="This period" icon={AlertTriangle}/><StatCard label="Critical" value="7" note="3 unresolved" icon={Zap} alert/><StatCard label="Warnings" value="19" note="4 unresolved" icon={Bell}/><StatCard label="Resolved" value="25 / 32" note="78% resolution rate" icon={Check}/></div><div className="toolbar"><div className="chips">{["All","Critical","Warning","Info"].map(x=><Button key={x} variant={severity===x?"default":"outline"} size="sm" onClick={()=>setSeverity(x)}>{x}</Button>)}</div><label className="search"><Search/><Input placeholder="Search errors..."/></label></div><Panel title="Error feed"><div className="table-scroll"><table><thead><tr>{["Timestamp","Severity","Category","Description","Estate","Status","Actions"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{errors.filter(e=>severity==="All"||e.severity===severity).map(e=><tr className="clickable-row" key={e.time+e.category} onClick={()=>setSelected(e)}><td className="data-text">{e.time}</td><td><Badge>{e.severity}</Badge></td><td>{e.category}</td><td>{e.description}</td><td>{e.estate}</td><td><Badge>{e.status}</Badge></td><td><RowActions labels={["View","Resolve","Dismiss"]}/></td></tr>)}</tbody></table></div></Panel>{selected&&<Drawer title="Error details" close={()=>setSelected(null)}><Badge>{selected.severity}</Badge><h3 className="drawer-heading">{selected.description}</h3><p className="drawer-copy">The gate controller stopped responding after three sequential heartbeat requests. Automatic reconnection was unsuccessful.</p><dl className="definition-list"><div><dt>Estate</dt><dd>{selected.estate}</dd></div><div><dt>Category</dt><dd>{selected.category}</dd></div><div><dt>Timestamp</dt><dd>{selected.time}</dd></div><div><dt>Affected resource</dt><dd className="data-text">gate_ctrl_NORTH_01</dd></div></dl><div className="code-block"><span>STACK INFO</span><code>ConnectionTimeout: heartbeat exceeded 30s<br/>at GateClient.poll (gateway.ts:184)<br/>retry_count: 3</code></div><Panel title="Resolution log"><p className="empty-copy">No resolution logged yet.</p></Panel><FormField label="Resolution note" placeholder="Add investigation notes..."/><div className="stack-actions"><Button><Check/>Mark resolved</Button><Button variant="outline">Add note</Button><Button variant="destructive">Escalate</Button></div></Drawer>}</>}

function StaffPage(){const [tab,setTab]=useState("Estate Managers");const [drawer,setDrawer]=useState(false);return <><PageHeader eyebrow="People" title="Staff & Managers" subtitle="Control access across the platform and estate teams."><Button><UserPlus/>Invite manager</Button></PageHeader><nav className="tabs"><button className={tab==="Platform Staff"?"active":""} onClick={()=>setTab("Platform Staff")}>Platform staff</button><button className={tab==="Estate Managers"?"active":""} onClick={()=>setTab("Estate Managers")}>Estate managers</button></nav><Panel title={tab}>{tab==="Estate Managers"?<SimpleTable headers={["Name","Email","Assigned estate","Last login","Status","Actions"]} rows={[["Sipho Dlamini","sipho@kyalamihills.co.za","Kyalami Hills","12 Jun · 13:58",<Badge>Active</Badge>,<Button variant="ghost" onClick={()=>setDrawer(true)}>View <ChevronRight/></Button>],["Thandi Nkosi","thandi@waterfallridge.co.za","Waterfall Ridge","12 Jun · 12:41",<Badge>Active</Badge>,<RowActions labels={["View","Message","Reassign","Deactivate"]}/>],["Lisa Adams","lisa@atlanticterraces.co.za","Atlantic Terraces","11 Jun · 17:02",<Badge>Active</Badge>,<RowActions labels={["View","Message","Reassign","Deactivate"]}/>]]}/>:<SimpleTable headers={["Name","Email","Role","Last login","Status","Actions"]} rows={[["Bryson Mabilo","bryson@estavo.co.za","Superadmin","12 Jun · 14:28",<Badge>Active</Badge>,<RowActions labels={["View","Edit"]}/>],["Naledi Mahlangu","naledi@estavo.co.za","Support","12 Jun · 11:18",<Badge>Active</Badge>,<RowActions labels={["View","Edit","Deactivate"]}/>],["Michael Botha","michael@estavo.co.za","Billing Admin","10 Jun · 09:44",<Badge tone="neutral">Inactive</Badge>,<RowActions labels={["View","Edit","Activate"]}/>]]}/>}</Panel>{drawer&&<Drawer title="Manager profile" close={()=>setDrawer(false)}><div className="profile-card"><div className="avatar">SD</div><div><h3>Sipho Dlamini</h3><p>sipho@kyalamihills.co.za</p><Badge>Active</Badge></div></div><dl className="definition-list"><div><dt>Assigned estate</dt><dd>Kyalami Hills</dd></div><div><dt>Phone</dt><dd>+27 82 555 0142</dd></div><div><dt>Last login</dt><dd>12 Jun · 13:58</dd></div></dl><h3>Last 10 activity entries</h3><ActivityList/><div className="stack-actions"><Button>Reassign estate</Button><Button variant="outline">Message</Button><Button variant="destructive">Deactivate</Button></div></Drawer>}</>}

function BillingPage(){return <><PageHeader eyebrow="Finance" title="Billing & Subscriptions" subtitle="Manage estate subscriptions and invoice history."><Button variant="outline"><Download/>Export CSV</Button></PageHeader><div className="stats-grid"><StatCard label="Active subscriptions" value="4" note="1 setup incomplete" icon={CreditCard}/><StatCard label="MRR" value="R 72 000.00" note="+4.2% month on month" icon={CircleDollarSign}/><StatCard label="Overdue" value="1" note="R 9 800.00 outstanding" icon={AlertTriangle} alert/><StatCard label="Upcoming renewals" value="4" note="Due in July" icon={RefreshCw}/></div><Panel title="Subscriptions"><SimpleTable headers={["Estate","Plan","Monthly fee","Billing contact","Status","Next invoice","Actions"]} rows={estates.slice(0,4).map(e=>[e.name,"Growth",e.mrr,e.manager,<Badge tone={e.status==="Suspended"?"error":"success"}>{e.status==="Suspended"?"Overdue":"Active"}</Badge>,"01 Jul 2026",<RowActions labels={["Edit","Suspend","Send invoice"]}/>])}/></Panel><Panel title="Invoice history"><SimpleTable headers={["Estate","Invoice #","Date","Amount","Status","Action"]} rows={estates.slice(0,4).map((e,i)=>[e.name,`INV-2026-06${12-i}`,"01 Jun 2026",e.mrr,<Badge tone={e.status==="Suspended"?"error":"success"}>{e.status==="Suspended"?"Overdue":"Paid"}</Badge>,<Button variant="ghost" size="sm"><Download/>PDF</Button>])}/></Panel></>}

function SettingsPage(){const [open,setOpen]=useState("Branding");const sections=["Branding","Integrations","Notification Rules","Security","Danger Zone"];return <><PageHeader eyebrow="Administration" title="Platform Settings" subtitle="Configure platform-wide defaults, services and security."/><div className="settings-list">{sections.map(section=><section className={`accordion ${section==="Danger Zone"?"danger-zone":""}`} key={section}><button onClick={()=>setOpen(open===section?"":section)}><span>{section==="Branding"&&<Building2/>}{section==="Integrations"&&<Zap/>}{section==="Notification Rules"&&<Bell/>}{section==="Security"&&<Shield/>}{section==="Danger Zone"&&<AlertTriangle/>}<b>{section}</b></span><ChevronDown className={open===section?"rotate":""}/></button>{open===section&&<div className="accordion-content">{section==="Branding"&&<div className="form-grid"><FormField label="Platform name" value="Estavo"/><FormField label="Support email" value="support@estavo.co.za"/><div className="upload-box"><Building2/><span><b>Platform logo</b><small>PNG, SVG or JPG · max 2MB</small></span><Button variant="outline">Upload</Button></div><Button>Save branding</Button></div>}{section==="Integrations"&&<IntegrationSettings/>}{section==="Notification Rules"&&<div className="form-grid"><FormField label="Alert when gate is offline for" value="5 minutes"/><FormField label="Billing overdue alert after" value="3 days"/><FormField label="Health score alert threshold" value="60"/><Button>Save rules</Button></div>}{section==="Security"&&<div className="form-grid"><ToggleRow label="Enforce two-factor authentication" description="Require 2FA for all platform staff." defaultOn/><FormField label="Session timeout (minutes)" value="60"/><FormField label="Audit log retention (days)" value="365"/><Button>Save security settings</Button></div>}{section==="Danger Zone"&&<div><p>These actions are destructive and cannot be undone.</p><div className="danger-actions"><div><b>Reset all platform settings</b><small>Restore configuration to defaults.</small></div><Button variant="destructive">Reset settings</Button></div><div className="danger-actions"><div><b>Wipe test data</b><small>Delete all non-production records.</small></div><Button variant="destructive">Wipe test data</Button></div></div>}</div>}</section>)}</div></>}

function Wizard({close}:{close:()=>void}){const [step,setStep]=useState(1);const [launched,setLaunched]=useState(false);const labels=["Estate profile","Gate configuration","App configurables","Resident import","Staff setup","Billing setup"];
  if(launched)return <div className="wizard-overlay"><div className="success-screen"><div className="success-mark"><Check/></div><p className="eyebrow">Estate launched</p><h1>Kingswood Park is ready</h1><p>Everything is configured. The estate manager can now begin onboarding residents.</p><div className="launch-checks">{["Estate created","2 gates configured","184 residents imported","6 staff members added","Billing set at R 18 500.00 / month"].map(x=><span key={x}><Check/>{x}</span>)}</div><div className="success-actions"><Button onClick={close}>Open estate <ChevronRight/></Button><Button variant="outline" onClick={()=>{setStep(1);setLaunched(false)}}>Add another estate</Button><Button variant="ghost" onClick={close}>Go to overview</Button></div></div></div>;
  return <div className="wizard-overlay"><aside className="wizard-sidebar"><div className="brand"><span>E</span><b>ESTAVO</b></div><p>New estate setup</p><ol>{labels.map((x,i)=><li className={step===i+1?"active":step>i+1?"complete":""} key={x}><span>{step>i+1?<Check/>:i+1}</span><div><b>{x}</b><small>Step {i+1} of 6</small></div></li>)}</ol><button className="wizard-exit" onClick={close}><X/>Exit setup</button></aside><main className="wizard-main"><div className="wizard-progress"><i style={{width:`${step/6*100}%`}}/></div><div className="wizard-content"><p className="eyebrow">Step {step} of 6</p><h1>{labels[step-1]}</h1><p className="wizard-intro">{wizardDescriptions[step-1]}</p>{step===1&&<WizardProfile/>}{step===2&&<WizardGates/>}{step===3&&<WizardConfig/>}{step===4&&<WizardResidents/>}{step===5&&<WizardStaff/>}{step===6&&<WizardBilling/>}<div className="wizard-actions"><Button variant="ghost" disabled={step===1} onClick={()=>setStep(step-1)}><ChevronLeft/>Back</Button><Button onClick={()=>step===6?setLaunched(true):setStep(step+1)}>{step===6?"Confirm & launch estate":"Continue"}<ChevronRight/></Button></div></div></main></div>}
const wizardDescriptions=["Tell us the essentials about this estate.","Connect each physical gate to the Estavo platform.","Set estate-wide defaults for access, emergencies and governance.","Bring the resident register into Estavo.","Add the operational team who will use the platform.","Choose a plan and configure the estate’s monthly billing."];
function WizardProfile(){return <div className="wizard-form"><div className="form-grid"><FormField label="Estate name" placeholder="e.g. Kingswood Park"/><SelectField label="Province" options={["GP","WC","KZN","LP","MP","NW","EC","NC","FS"]}/><FormField label="Physical address" placeholder="Street address"/><FormField label="Number of units" type="number" placeholder="0"/><FormField label="Google Maps link" placeholder="https://maps.google.com/..."/><FormField label="Security contact number" placeholder="+27"/><SelectField label="Estate type" options={["Residential","Lifestyle","Retirement","Mixed Use"]}/><FormField label="Website (optional)" placeholder="https://"/></div></div>}
function WizardGates(){return <div className="wizard-form"><SelectField label="Number of gates" options={["1","2","3","4","5"]}/>{[1,2].map(i=><div className="repeat-card" key={i}><div className="panel-header"><h3>Gate {i}</h3><Badge>{i===1?"Online":"Pending"}</Badge></div><div className="form-grid"><FormField label="Gate name" value={i===1?"North vehicle gate":"South pedestrian gate"}/><SelectField label="Type" options={["Vehicle","Pedestrian","Boom","Sliding"]}/><FormField label="Hardware IP" placeholder="192.168.1.100"/><label className="field"><span>Device key</span><div className="copy-field"><code>EST-{i}A8F-82KQ-91T</code><Button variant="ghost" size="icon"><Copy/></Button></div></label></div><Button variant="outline"><TestTube2/>Test connection</Button></div>)}<Button variant="outline"><Plus/>Add another gate</Button></div>}
function WizardConfig(){return <div className="wizard-form config-sections"><ConfigGroup title="Access & Gate"><RangeField label="Gate hold duration" min="0.5" max="5" value="1.5" suffix="s"/><RangeField label="Gate undo window" min="0" max="30" value="5" suffix="s"/></ConfigGroup><ConfigGroup title="Emergency"><RangeField label="Emergency hold duration" min="3" max="10" value="5" suffix="s"/><RangeField label="Emergency undo window" min="0" max="60" value="5" suffix="s"/></ConfigGroup><ConfigGroup title="Guest Access"><div className="form-grid"><FormField label="Guest code length" value="4"/><SelectField label="Guest code type" options={["Alphanumeric","Numeric only"]}/></div><RangeField label="Max active guest codes per resident" min="1" max="50" value="10"/><RangeField label="Guest code max validity" min="1" max="365" value="30" suffix="days"/><ToggleRow label="Require guest ID on entry" description="Guests must present identification."/></ConfigGroup><ConfigGroup title="Governance"><div className="form-grid"><FormField label="Approval threshold (ZAR)" value="5000"/><FormField label="Votes required" value="2"/><FormField label="Quote minimum" value="3"/><FormField label="Unassigned ticket warning (hours)" value="12"/></div><ToggleRow label="Emergency auto-notify trustees" description="Notify trustees automatically when an emergency is triggered." defaultOn/></ConfigGroup><ConfigGroup title="Community"><ToggleRow label="Community board enabled" description="Residents can access the community board." defaultOn/><ToggleRow label="Anonymous posting allowed" description="Residents may hide their identity from other residents." defaultOn/><ToggleRow label="Events RSVP enabled" description="Allow event responses in the app." defaultOn/><ToggleRow label="Amenities booking enabled" description="Allow residents to reserve estate amenities."/></ConfigGroup></div>}
function WizardResidents(){const [mode,setMode]=useState("Upload CSV");return <div className="wizard-form"><div className="segmented"><button className={mode==="Upload CSV"?"active":""} onClick={()=>setMode("Upload CSV")}>Upload CSV</button><button className={mode==="Add Manually"?"active":""} onClick={()=>setMode("Add Manually")}>Add manually</button></div>{mode==="Upload CSV"?<><div className="dropzone"><Download/><h3>Drop your resident CSV here</h3><p>or click to browse · CSV up to 10MB</p><Button variant="outline">Choose file</Button></div><SimpleTable headers={["Row","Unit","Type","Name","Email","Status"]} rows={[["1","12","Owner","Nandi Mokoena","nandi@example.co.za",<Badge>Valid</Badge>],["2","18","Tenant","James van Wyk","james@example.co.za",<Badge>Valid</Badge>],["3","—","Owner","Ayanda Khumalo","ayanda@example.co.za",<Badge tone="error">Error</Badge>]]}/><Button>Confirm import — 184 valid / 1 skipped</Button></>:<><div className="repeat-card"><div className="form-grid"><FormField label="Unit"/><SelectField label="Type" options={["Owner","Tenant"]}/><FormField label="Name"/><FormField label="Email"/><FormField label="Phone"/></div></div><Button variant="outline"><Plus/>Add another resident</Button></>}</div>}
function WizardStaff(){return <div className="wizard-form">{[1,2].map(i=><div className="repeat-card" key={i}><div className="panel-header"><h3>Staff member {i}</h3>{i>1&&<Button variant="ghost" size="icon"><X/></Button>}</div><div className="form-grid"><FormField label="Name"/><FormField label="Email"/><SelectField label="Role" options={["Security Guard","Gate Operator","Maintenance","Cleaner","Other"]}/></div></div>)}<div className="header-actions"><Button variant="outline"><Plus/>Add another</Button><Button variant="ghost">Skip for now</Button></div></div>}
function WizardBilling(){const [plan,setPlan]=useState("Growth");return <div className="wizard-form"><div className="plan-grid">{[["Starter","Core access tools"],["Growth","Operations & governance"],["Enterprise","Advanced portfolio controls"]].map(([p,d])=><button className={plan===p?"selected":""} onClick={()=>setPlan(p)} key={p}><span>{plan===p?<Check/>:<WalletCards/>}</span><h3>{p}</h3><p>{d}</p></button>)}</div><FormField label="Custom monthly fee (ZAR)" value="R 18 500.00" mono/><div className="form-grid"><FormField label="Billing contact name"/><FormField label="Billing email"/><FormField label="Phone"/><FormField label="Company name (optional)"/></div><div className="segmented"><button className="active">Connect Yoco</button><button>Invoice monthly</button></div><FormField label="Billing start date" type="date"/></div>}

export function EstavoSuperadmin(){const [view,setView]=useState<View>("overview");const [collapsed,setCollapsed]=useState(false);const [mobile,setMobile]=useState(false);const [estate,setEstate]=useState<string|null>(null);const [wizard,setWizard]=useState(false);const nav=[{id:"overview",label:"Overview",icon:LayoutDashboard},{id:"estates",label:"Estates",icon:Building2},{label:"Analytics",icon:BarChart3,children:[{id:"health",label:"Health & Performance"},{id:"revenue",label:"Revenue & Financials"},{id:"errors",label:"System Errors & Failures"}]},{id:"staff",label:"Staff & Managers",icon:Users},{id:"billing",label:"Billing & Subscriptions",icon:CreditCard},{id:"settings",label:"Platform Settings",icon:Settings}] as const;
 const navigate=(id:View)=>{setView(id);setEstate(null);setMobile(false)};
 return <div className={`app-shell ${collapsed?"sidebar-collapsed":""}`}><aside className={`sidebar ${mobile?"mobile-open":""}`}><div className="sidebar-brand"><div className="brand"><span>E</span>{!collapsed&&<b>ESTAVO</b>}</div><Button variant="ghost" size="icon" onClick={()=>setCollapsed(!collapsed)} aria-label="Collapse sidebar">{collapsed?<ChevronRight/>:<ChevronLeft/>}</Button></div><nav className="sidebar-nav">{nav.map((item,i)=><div key={item.label} className="nav-group">{"id" in item&&item.id?<button className={view===item.id&&!estate?"active":""} onClick={()=>navigate(item.id as View)}><item.icon/><span>{item.label}</span></button>:<div className="nav-parent"><item.icon/><span>{item.label}</span></div>}{"children" in item&&item.children&&<div className="nav-children">{item.children.map(child=><button className={view===child.id&&!estate?"active":""} onClick={()=>navigate(child.id as View)} key={child.id}>{child.label}</button>)}</div>}</div>)}</nav><div className="sidebar-user"><div className="avatar">BM</div>{!collapsed&&<div><b>Bryson Mabilo</b><span>Superadmin</span></div>}<Ellipsis/></div></aside>{mobile&&<button className="mobile-scrim" onClick={()=>setMobile(false)} aria-label="Close menu"/>}<main className="app-main"><div className="mobile-header"><Button variant="ghost" size="icon" onClick={()=>setMobile(true)}><Menu/></Button><div className="brand"><span>E</span><b>ESTAVO</b></div><div className="avatar">BM</div></div><div className="page-content">{estate?<EstateDetail name={estate} close={()=>setEstate(null)}/>:<>{view==="overview"&&<Overview openEstate={setEstate} navigate={navigate}/>} {view==="estates"&&<EstatesPage openEstate={setEstate} openWizard={()=>setWizard(true)}/>} {view==="health"&&<HealthPage openEstate={setEstate}/>} {view==="revenue"&&<RevenuePage/>} {view==="errors"&&<ErrorsPage/>} {view==="staff"&&<StaffPage/>} {view==="billing"&&<BillingPage/>} {view==="settings"&&<SettingsPage/>}</>}</div></main>{wizard&&<Wizard close={()=>{setWizard(false);navigate("overview")}}/>}</div>;
}

function SimpleTable({headers,rows}:{headers:string[];rows:React.ReactNode[][]}){return <div className="table-scroll"><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
function RowActions({labels}:{labels:string[]}){return <div className="row-actions">{labels.slice(0,2).map(x=><Button variant="ghost" size="sm" key={x}>{x}</Button>)}{labels.length>2&&<Button variant="ghost" size="icon" title={labels.slice(2).join(", ")}><MoreHorizontal/></Button>}</div>}
function ActivityList(){return <div className="activity-list">{[["Updated gate configuration","12 Jun · 13:42"],["Resolved ticket #MT-1034","12 Jun · 12:19"],["Invited resident · Unit 81","12 Jun · 10:07"],["Exported access log","11 Jun · 16:33"]].map(([a,t])=><div key={a}><span className="activity-icon"><Activity/></span><div><b>{a}</b><small>{t}</small></div></div>)}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={close}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="panel-header"><h2>{title}</h2><Button variant="ghost" size="icon" onClick={close}><X/></Button></div>{children}</section></div>}
function Drawer({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="overlay" onMouseDown={close}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><div className="panel-header"><div><p className="eyebrow">Estavo platform</p><h2>{title}</h2></div><Button variant="ghost" size="icon" onClick={close}><X/></Button></div>{children}</aside></div>}
function FormField({label,placeholder,type="text",value,mono}:{label:string;placeholder?:string;type?:string;value?:string;mono?:boolean}){return <label className="field"><span>{label}</span><Input type={type} placeholder={placeholder} defaultValue={value} className={mono?"data-text":""}/></label>}
function SelectField({label,options}:{label:string;options:string[]}){return <label className="field"><span>{label}</span><select>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function ToggleRow({label,description,defaultOn=false}:{label:string;description:string;defaultOn?:boolean}){return <div className="toggle-row"><div><b>{label}</b><small>{description}</small></div><Switch defaultChecked={defaultOn}/></div>}
function ConfigGroup({title,children}:{title:string;children:React.ReactNode}){return <section><h2>{title}</h2>{children}</section>}
function RangeField({label,min,max,value,suffix}:{label:string;min:string;max:string;value:string;suffix?:string}){return <label className="range-field"><span><b>{label}</b><output>{value}{suffix}</output></span><input type="range" min={min} max={max} defaultValue={value} step="0.5"/></label>}
function IntegrationSettings(){return <div className="integration-list">{[["Twilio","SMS and WhatsApp delivery"],["Resend","Transactional email"],["Yoco","Subscription payments"],["barKoder SDK","Gate code scanning"]].map(([x,d])=><div key={x}><span className="icon-box"><Zap/></span><div><b>{x}</b><small>{d}</small></div><Badge>Connected</Badge><Button variant="outline" size="sm">Test</Button></div>)}</div>}
function ChartBars({dataKey}:{dataKey:"health"|"adoption"}){return <div className="chart-box"><ResponsiveContainer><BarChart data={estates} margin={{left:0,right:0}}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" hide/><YAxis hide domain={[0,100]}/><Tooltip content={<MiniTooltip/>}/><Bar dataKey={dataKey} radius={[3,3,0,0]}>{estates.map((e,i)=><Cell key={i} fill={e[dataKey]>=80?"var(--success)":e[dataKey]>=60?"var(--warning)":"var(--error)"}/>)}</Bar></BarChart></ResponsiveContainer></div>}
function ComboChart(){return <div className="chart-box"><ResponsiveContainer><BarChart data={months}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip content={<MiniTooltip/>}/><Bar dataKey="tickets" fill="var(--chart-muted)"/><Line type="monotone" dataKey="resolution" stroke="var(--chart-foreground)" strokeWidth={2}/></BarChart></ResponsiveContainer></div>}
function DualBar(){return <div className="chart-box"><ResponsiveContainer><BarChart data={months}><XAxis dataKey="month"/><YAxis hide/><Tooltip content={<MiniTooltip/>}/><Bar dataKey="revenue" fill="var(--chart-foreground)"/><Bar dataKey="expenses" fill="var(--chart-muted)"/></BarChart></ResponsiveContainer></div>}
function LineOnly(){return <div className="chart-box"><ResponsiveContainer><LineChart data={months}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="month"/><YAxis hide/><Tooltip content={<MiniTooltip/>}/><Line type="monotone" dataKey="profit" stroke="var(--chart-foreground)" strokeWidth={2}/></LineChart></ResponsiveContainer></div>}
function RevenuePie(){return <div className="chart-box"><ResponsiveContainer><PieChart><Tooltip content={<MiniTooltip/>}/><Pie data={estates.slice(0,4)} dataKey="units" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={3}>{estates.slice(0,4).map((_,i)=><Cell key={i} fill={["var(--chart-foreground)","var(--chart-muted)","var(--muted-foreground)","var(--border-strong)"][i]}/>)}</Pie></PieChart></ResponsiveContainer></div>}