import { pgTable, uuid, text, integer, jsonb, boolean, numeric, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const estates = pgTable("estates", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  address: text("address"),
  mapsLink: text("maps_link"),
  logoUrl: text("logo_url"),
  unitCount: integer("unit_count"),
  timezone: text("timezone").default("Africa/Johannesburg"),
  province: text("province"),
  estateType: text("estate_type"),
  features: jsonb("features").default({
    community_posts: false,
    community_events: false,
    amenity_bookings: false,
    weekly_maintenance: false,
    contractor_directory: false,
    emergency_button: true,
    walkin_gate_pin: false,
    walkin_gate_biometric_info: false,
    parcel_delivery_codes: true,
    non_emergency_alert: true,
    noise_complaints: false,
    staff_incident_reporting: true,
    report_voting: false,
    community_mute_hours: false,
    amenity_waitlist: false,
    amenity_damage_reporting: false,
    vehicle_register: false,
    vehicle_register_mandatory: false,
    account_standing_flag: false,
    document_library: false,
    anonymous_posts: true,
    resident_chooses_anonymity: true,
    post_moderation: false,
    approval_requests: true,
    trustee_portal: false,
    corporate_dashboard: false,
    management_broadcasts: true,
    email_resident_tool: true,
  }),
  communityConfig: jsonb("community_config").default({
    mute_hours_start: "22:00",
    mute_hours_end: "07:00",
  }),
  guestCodeConfig: jsonb("guest_code_config").default({
    available_durations_hours: [2, 6, 12, 24, 48],
    max_active_codes_per_unit: 10,
    max_active_codes_per_resident: null,
    code_limit_type: "per_unit",
    allow_custom_duration: false,
    allow_extension: true,
    max_extensions: 1,
    code_format: "pin_and_qr",
  }),
  securityConfig: jsonb("security_config").default({
    resident_hold_seconds: 3,
    security_hold_seconds: 2,
    undo_window_seconds: 5,
    gate_rate_limit_per_minute: 10,
    emergency_hold_seconds: 5,
    emergency_confirmation_required: false,
    false_alarm_strikes_before_suspension: 3,
    emergency_suspension_hours: 24,
  }),
  escalationConfig: jsonb("escalation_config").default({
    unassigned_threshold_hours: 12,
    open_threshold_hours: 48,
    manager_escalation_hours: 72,
  }),
  gates: jsonb("gates").default([]),
  gateGroups: jsonb("gate_groups").default([]),
  approvalConfig: jsonb("approval_config").default({
    approval_threshold_rands: 5000,
    votes_required: 2,
    quotes_required: 3,
    notify_trustees_on_emergency: true,
  }),
  paymentStatus: text("payment_status").default("active"),
  paymentOverdueSince: timestamp("payment_overdue_since", { withTimezone: true }),
  stripeCustomerId: text("stripe_customer_id"),
  stripeSubscriptionId: text("stripe_subscription_id"),
  monthlyFeeRands: numeric("monthly_fee_rands", { precision: 10, scale: 2 }),
  planNotes: text("plan_notes"),
  status: text("status").default("active"),
  onboardingComplete: boolean("onboarding_complete").default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const insertEstateSchema = createInsertSchema(estates).omit({ id: true, createdAt: true });
export type InsertEstate = z.infer<typeof insertEstateSchema>;
export type Estate = typeof estates.$inferSelect;
